# Generated by Django 5.0 on 2023-12-06 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('contact_details', models.TextField(verbose_name='Contact Details')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('on_time_delivery_rate', models.FloatField(blank=True, null=True, verbose_name='On Time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(blank=True, null=True, verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(blank=True, null=True, verbose_name='Average Response Time')),
                ('fulfillment_rate', models.FloatField(blank=True, null=True, verbose_name='Fulfillment Rate')),
            ],
            options={
                'ordering': ['vendor_id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_number', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('delivery_date', models.DateTimeField(verbose_name='Delivery Date')),
                ('items', models.JSONField(verbose_name='Items')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20, verbose_name='Status')),
                ('quality_rating', models.FloatField(blank=True, null=True, verbose_name='Quality Rating')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='Issue Date')),
                ('acknowledgment_date', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledgment Date')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vendor', verbose_name='Vendor')),
            ],
            options={
                'ordering': ['-order_date', 'po_number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('on_time_delivery_rate', models.FloatField(verbose_name='On Time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(verbose_name='Average Response Time')),
                ('fulfillment_rate', models.FloatField(verbose_name='Fulfillment Rate')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vendor', verbose_name='vendor')),
            ],
        ),
    ]
