# Generated by Django 5.0 on 2023-12-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Vendor Code'),
            preserve_default=False,
        ),
    ]
